import { migrate } from 'drizzle-orm/better-sqlite3/migrator';

import { closeDb, db } from './index.js';

/**
 * Applies any migrations generated by `npm run db:generate`.
 *
 * The legacy tables are created by `bootstrap.ts` on startup, so this only has
 * work to do once you start evolving the schema through drizzle-kit.
 */
migrate(db, { migrationsFolder: './drizzle' });
console.log('migrations applied');
closeDb();
